export const works = {
  apps: [
    {
      title: "dumb-slides-maker",
      date: new Date(2023, 9),
      url: "https://dumb-slides-maker.vercel.app/",
      screenshot: "/screenshots/dumbslidesmaker.png",
      description: "markdownでダサスライド作成",
      techStack: [
        { name: "Svelte", icon: "/tech-logo/svelte.png" },
        { name: "UnoCSS", icon: "/tech-logo/unocss.svg" },
        { name: "Marpit", icon: "/tech-logo/marp.png" },
      ],
      isTeam: false,
    },
    {
      title: "POLYFORCE",
      date: new Date(2023, 9),
      url: "https://unityroom.com/games/polyforce",
      screenshot: "/screenshots/polyforce.png",
      description: "スピーディー重力反転アクションゲーム",
      techStack: [{ name: "Unity", icon: "/tech-logo/unity.png" }],
      isTeam: true,
    },
    {
      title: "moodle-line-bot",
      date: new Date(2023, 3),
      url: "https://github.com/9rotama/moodle-line-bot",
      screenshot: "/screenshots/moodlelinebot.png",
      description: "moodleのコース内の予定を表示・共有できるlinebot",
      techStack: [
        { name: "TypeScript", icon: "/tech-logo/ts.png" },
        { name: "Prisma", icon: "/tech-logo/prisma.png" },
      ],
      isTeam: false,
    },
    {
      title: "re-translate-bot",
      date: new Date(2022, 6),
      url: "https://github.com/9rotama/re-translate-bot",
      screenshot: "/screenshots/re-translate-bot.jpeg",
      description: "ムダ翻訳bot",
      techStack: [{ name: "Python", icon: "/tech-logo/python.webp" }],
      isTeam: false,
    },
    {
      title: "9rtm.com",
      date: new Date(2022, 5),
      url: "https://github.com/9rotama/9rtm.com",
      screenshot: "/screenshots/9rtmcom.png",
      description: "ポートフォリオ",
      techStack: [
        { name: "Next.js", icon: "/tech-logo/next-js.svg" },
        { name: "TypeScript", icon: "/tech-logo/ts.png" },
        { name: "three.js", icon: "/tech-logo/three.png" },
      ],
      isTeam: false,
    },
  ],
};
